-- ============================================================================
-- PROJECT: FinVantage - Personal & Business Finance Management System
-- SCRIPT: Sample Seed Data for Demonstration & Evaluation
-- ============================================================================

-- 1. Insert Initial Users
-- Password hash for 'Admin@123': SHA-256 of 'Admin@123' + salt
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, PHONE_NUMBER, STATUS)
VALUES ('Alexander Vance', 'alex.vance@finvantage.com', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'ADMIN', '+1-555-0199', 'ACTIVE');

INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, PHONE_NUMBER, STATUS)
VALUES ('Sophia Rodriguez', 'sophia.r@example.com', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'USER', '+1-555-0245', 'ACTIVE');

-- 2. Insert Default Categories
-- User 1 Categories (Alexander)
INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Salary & Compensation', 'INCOME', '#2ECC71', 'briefcase');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Investment Dividends', 'INCOME', '#1ABC9C', 'trending-up');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Consulting & Freelance', 'INCOME', '#3498DB', 'laptop');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Housing & Mortgage', 'EXPENSE', '#E74C3C', 'home');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Groceries & Dining', 'EXPENSE', '#E67E22', 'shopping-cart');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Technology & Cloud', 'EXPENSE', '#9B59B6', 'server');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Healthcare & Medical', 'EXPENSE', '#F39C12', 'heart');

INSERT INTO CATEGORIES (USER_ID, NAME, CATEGORY_TYPE, COLOR_HEX, ICON_NAME) 
VALUES (1, 'Travel & Transport', 'EXPENSE', '#34495E', 'plane');

-- 3. Insert Accounts (Demonstrating Polymorphism: Savings, Checking, Investment)
-- Account 1: High-Yield Savings
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, CURRENCY, INTEREST_RATE, OVERDRAFT_LIMIT, MINIMUM_BALANCE, STATUS)
VALUES (1, 'ACC-SAV-1001-ORCL', 'Premier Wealth High-Yield', 'SAVINGS', 18500.00, 'USD', 4.75, 0.00, 500.00, 'ACTIVE');

-- Account 2: Business / Personal Checking
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, CURRENCY, INTEREST_RATE, OVERDRAFT_LIMIT, MINIMUM_BALANCE, STATUS)
VALUES (1, 'ACC-CHK-2002-ORCL', 'Apex Everyday Operating', 'CHECKING', 4250.75, 'USD', 0.10, 1500.00, 0.00, 'ACTIVE');

-- Account 3: Growth Investment Portfolio
INSERT INTO ACCOUNTS (USER_ID, ACCOUNT_NUMBER, ACCOUNT_NAME, ACCOUNT_TYPE, BALANCE, CURRENCY, INTEREST_RATE, OVERDRAFT_LIMIT, MINIMUM_BALANCE, PORTFOLIO_RISK, STATUS)
VALUES (1, 'ACC-INV-3003-ORCL', 'Vanguard S&P Index Portfolio', 'INVESTMENT', 34200.50, 'USD', 7.80, 0.00, 1000.00, 'MODERATE', 'ACTIVE');

-- 4. Insert Budgets for Current Period
INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, MONTH_YEAR, BUDGET_LIMIT, ALERT_THRESHOLD)
VALUES (1, 4, TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM'), 2200.00, 85.00); -- Housing

INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, MONTH_YEAR, BUDGET_LIMIT, ALERT_THRESHOLD)
VALUES (1, 5, TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM'), 800.00, 80.00);  -- Groceries

INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, MONTH_YEAR, BUDGET_LIMIT, ALERT_THRESHOLD)
VALUES (1, 6, TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM'), 350.00, 75.00);  -- Tech / Cloud

INSERT INTO BUDGETS (USER_ID, CATEGORY_ID, MONTH_YEAR, BUDGET_LIMIT, ALERT_THRESHOLD)
VALUES (1, 8, TO_CHAR(CURRENT_TIMESTAMP, 'YYYY-MM'), 600.00, 90.00);  -- Travel

-- 5. Insert Realistic Transactions
-- Income 1: Monthly Corporate Salary
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9001', NULL, 2, 1, 7500.00, 'INCOME', CURRENT_TIMESTAMP - 18, 'September Senior Engineering Payroll Direct Deposit', 'COMPLETED');

-- Income 2: Quarterly Dividend Payout
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9002', NULL, 3, 2, 850.50, 'INCOME', CURRENT_TIMESTAMP - 14, 'Q3 Index Fund Dividend Reinvestment', 'COMPLETED');

-- Expense 1: Monthly Apartment Lease / Mortgage
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9003', 2, NULL, 4, 1850.00, 'EXPENSE', CURRENT_TIMESTAMP - 12, 'Metropolitan Tower Apartment Lease', 'COMPLETED');

-- Expense 2: Organic Supermarket
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9004', 2, NULL, 5, 234.60, 'EXPENSE', CURRENT_TIMESTAMP - 8, 'Whole Foods Bi-Weekly Grocery Restock', 'COMPLETED');

-- Expense 3: Cloud Infrastructure & AI Dev Servers
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9005', 2, NULL, 6, 178.40, 'EXPENSE', CURRENT_TIMESTAMP - 5, 'Oracle Cloud Infrastructure & GitHub Enterprise Billing', 'COMPLETED');

-- Expense 4: Weekend Dining & Bakery
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9006', 2, NULL, 5, 86.25, 'EXPENSE', CURRENT_TIMESTAMP - 2, 'Bistro Artisan Family Dinner', 'COMPLETED');

-- Transfer: Monthly Auto-Savings Allocation
INSERT INTO TRANSACTIONS (TX_REF, SOURCE_ACCOUNT_ID, DEST_ACCOUNT_ID, CATEGORY_ID, AMOUNT, TX_TYPE, TX_DATE, DESCRIPTION, STATUS)
VALUES ('TX-ORCL-9007', 2, 1, NULL, 2000.00, 'TRANSFER', CURRENT_TIMESTAMP - 1, 'Automated Monthly Emergency Fund Transfer', 'COMPLETED');

-- 6. Insert Initial Audit Log Record
INSERT INTO AUDIT_LOGS (ACTION_TYPE, TABLE_NAME, RECORD_ID, USER_ID, DETAILS)
VALUES ('SYSTEM_INITIALIZATION', 'DATABASE', 1, 1, 'FinVantage schema and seed records successfully provisioned on Oracle Database.');

COMMIT;
